version: 0.2

env:
  variables:
    ECR_REPO_URI: "306266123975.dkr.ecr.ap-south-1.amazonaws.com/newmetadata"
    FRONTEND_BUCKET: "yourfrontendbucketfilesharingmetadataservice"
    LAMBDA_FUNCTION_NAME: "uploadmetadat"
    ECS_CONTAINER_NAME: "metadata-container"
    DB_SECRET_ID: "my-db-secret"  # update with your secret name

phases:
  install:
    runtime-versions:
      nodejs: 14
      docker: 19
    commands:
      - echo "ðŸ§¼ Cleaning and updating system packages..."
      - yum clean all
      - yum update -y
      - echo "ðŸ“¦ Installing jq and MySQL client..."
      - yum install -y mysql jq

  pre_build:
    commands:
      - echo "ðŸ” Retrieving DB credentials from Secrets Manager..."
      - export DB_USER=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ID --query SecretString --output text | jq -r '.username')
      - export DB_PASS=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ID --query SecretString --output text | jq -r '.password')
      - echo "ðŸ”‘ Logging into Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin "${ECR_REPO_URI%%/*}"
      - export IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}"

  build:
    commands:
      - echo "ðŸ³ Building Docker image..."
      - docker build -t "$ECR_REPO_URI:$IMAGE_TAG" ./backend
      - docker push "$ECR_REPO_URI:$IMAGE_TAG"
      - echo "ðŸŒ Syncing frontend files to S3..."
      - aws s3 sync ./frontend "s3://$FRONTEND_BUCKET" --delete

  post_build:
    commands:
      - cd lambda/generatePresigned
      - npm install || echo "npm install failed, skipping pip install"
      - zip -r ../../generatePresigned.zip *
      - cd ../../
      - echo "ðŸš€ Updating Lambda function..."
      - aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --zip-file fileb://generatePresigned.zip
      - echo "ðŸ“ Creating imagedefinitions.json for ECS..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECS_CONTAINER_NAME" "$ECR_REPO_URI:$IMAGE_TAG" > pipeline/imagedefinitions.json

artifacts:
  files:
    - pipeline/imagedefinitions.json
